# Generated by Django 4.1.6 on 2023-03-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('position', models.CharField(max_length=30)),
                ('interactive_board', models.BooleanField()),
                ('teacher_pc', models.BooleanField()),
                ('teacher_notebook', models.BooleanField()),
                ('flip_chart', models.BooleanField()),
                ('sink', models.BooleanField()),
                ('data_projector', models.BooleanField()),
                ('ethernet_cable', models.BooleanField()),
            ],
            options={
                'db_table': 'Classrooms',
            },
        ),
    ]
