# Generated by Django 4.1.6 on 2023-03-18 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.IntegerField(default=160706211180770873710670634260381819070, primary_key=True, serialize=False)),
                ('student_class', models.CharField(max_length=30)),
                ('student_group', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(max_length=30)),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10)),
                ('lesson', models.IntegerField()),
                ('teacher', models.CharField(max_length=30)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, default=None, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom')),
            ],
            options={
                'db_table': 'Timetables',
            },
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.CheckConstraint(check=models.Q(('valid_to__isnull', True), ('valid_to__gte', models.F('valid_from')), _connector='OR'), name='kontrola_datumu_prekryvania'),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lesson', 'day', 'student_group', 'student_class', 'valid_from')},
        ),
    ]
