# Generated by Django 4.1.6 on 2023-02-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='subject',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
