# Generated by Django 4.1.6 on 2023-02-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0002_timetable_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='subject',
            field=models.CharField(default='GEO', max_length=30),
        ),
    ]
