# Generated by Django 4.1.6 on 2023-02-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Timetable', '0004_alter_timetable_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timetable',
            name='student_group',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('lesson', 'day', 'student_group', 'student_class')},
        ),
    ]
