# Generated by Django 4.1.6 on 2023-02-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Timetable', '0001_initial'),
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Substitution',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('new_lesson', models.IntegerField(blank=True, null=True)),
                ('new_teacher', models.CharField(max_length=30)),
                ('new_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Timetable.timetable')),
            ],
            options={
                'db_table': 'Substitutions',
                'unique_together': {('date', 'timetable')},
            },
        ),
    ]
