# Generated by Django 4.1.6 on 2023-02-20 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Classroom', '0001_initial'),
        ('Substitution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='new_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom'),
        ),
    ]
