# Generated by Django 4.1.6 on 2023-02-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Substitution', '0002_alter_substitution_new_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substitution',
            name='new_teacher',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
