# Generated by Django 4.1.6 on 2023-03-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('lesson', models.IntegerField()),
                ('teacher', models.CharField(max_length=30)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Classroom.classroom')),
            ],
            options={
                'db_table': 'Reservations',
                'unique_together': {('date', 'lesson', 'classroom')},
            },
        ),
    ]
